### ISSUE TITLE
API rate limit exceeded by Mega-Linter task

### ISSUE THREAD

**Issue by csillag** [oasisprotocol/oasis-wallet-web#1013]
While the CI pipeline was executed for [one of the PRs](https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/3104092381/jobs/5028166645), we got this error.

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/megalinter-0.1-py3.9.egg/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/usr/local/lib/python3.9/site-packages/megalinter-0.1-py3.9.egg/megalinter/MegaLinter.py", line 175, in run
    reporter.produce_report()
  File "/usr/local/lib/python3.9/site-packages/megalinter-0.1-py3.9.egg/megalinter/reporters/GithubCommentReporter.py", line 88, in produce_report
    repo = g.get_repo(github_repo)
  File "/usr/local/lib/python3.9/site-packages/PyGithub-1.55-py3.9.egg/github/MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/usr/local/lib/python3.9/site-packages/PyGithub-1.55-py3.9.egg/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/PyGithub-1.55-py3.9.egg/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for installation ID 9263670.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

Apparently, something needs to be adjusted...

**Comment by nvuillam** [comment]
@csillag you should upgrade to MegaLinter v6: `npx mega-linter-runner@latest --upgrade` , it is much better than v5 , and smaller docker images :)

If your issue is still happening after, I'll catch such error so at least it won't make the job fail and you'll have the result in console logs anyway :)

**Comment by tjanez** [comment]
Thanks for chiming in @nvuillam :slightly_smiling_face:

> @csillag you should upgrade to MegaLinter v6: `npx mega-linter-runner@latest --upgrade` , it is much better than v5 , and smaller docker images :)

We'll take a look into upgrading to MegaLinter v6.

> Maybe you have a self hosted runner and other jobs eats all the API calls ?

AFAIK, we don't use any self hosted runners...
