### ISSUE TITLE
RpcError Response Error

### ISSUE THREAD

**Issue by rochelle-norman** [oasisprotocol/oasis-wallet-web#1781]
Steps to reproduce

1. Visit https://wallet.oasis.io/ or run the repository locally and visit http://localhost:3000/
2. Observe you cannot access the wallet and receive the below response error

```
Error: callUnary method https://grpc.oasis.dev/oasis-core.Beacon/GetEpoch: RpcError: Http response at 400 or 500 level, http status code: 0

The above error occurred in task selectNetwork1
    created by selectNetwork1
    created by anonymous
    created by takeLatest(network/initializeNetwork,network/selectNetwork,persist/setUnlockedRootState,persist/resetRootState,&_RECEIVE_INIT_STATE, )
    created by rootSagas1
    created by rootSagas1
Tasks cancelled due to error:
takeLatest(network/initializeNetwork,network/selectNetwork,persist/setUnlockedRootState,persist/resetRootState,&_RECEIVE_INIT_STATE, )
takeLatest(persist/resetRootState, )

Error: callUnary method https://grpc.oasis.dev/oasis-core.Beacon/GetEpoch: RpcError: Http response at 400 or 500 level, http status code: 0
    at https://wallet.oasis.io/index.7c90b354.js:87:119
Cause stack:
Error: Http response at 400 or 500 level, http status code: 0
    at new E1 (https://wallet.oasis.io/index.7c90b354.js:93:17533)
    at Y4 (https://wallet.oasis.io/index.7c90b354.js:93:40568)
    at qc1.<anonymous> (https://wallet.oasis.io/index.7c90b354.js:93:40295)
    at Jb1 (https://wallet.oasis.io/index.7c90b354.js:93:27940)
    at O1 (https://wallet.oasis.io/index.7c90b354.js:93:27743)
    at yc1 (https://wallet.oasis.io/index.7c90b354.js:93:35281)
    at Ac1 (https://wallet.oasis.io/index.7c90b354.js:93:36050)
    at d.W (https://wallet.oasis.io/index.7c90b354.js:93:37662)
    at d.R (https://wallet.oasis.io/index.7c90b354.js:93:37641)
End of cause stack
Invocation stack:
Error
    at NodeInternal1.value (https://wallet.oasis.io/index.7c90b354.js:81:112125)
    at NodeInternal1.value (https://wallet.oasis.io/index.7c90b354.js:93:493)
    at runCallEffect1 (https://wallet.oasis.io/index.7c90b354.js:74:106331)
    at runEffect1 (https://wallet.oasis.io/index.7c90b354.js:74:111824)
    at digestEffect1 (https://wallet.oasis.io/index.7c90b354.js:74:112312)
    at next1 (https://wallet.oasis.io/index.7c90b354.js:74:112815)
    at proc1 (https://wallet.oasis.io/index.7c90b354.js:74:112516)
    at runEffect1 (https://wallet.oasis.io/index.7c90b354.js:74:111770)
    at digestEffect1 (https://wallet.oasis.io/index.7c90b354.js:74:112312)
    at https://wallet.oasis.io/index.7c90b354.js:74:107771
End of invocation stack
```

**Comment by rochelle-norman** [comment]
I can't add labels

**Comment by lubej** [comment]
Hi @rochelle-norman,

please check [https://status.oasis.io/](https://status.oasis.io/), currently there is a Mainnet upgrade in progress.

Thanks for understanding.

**Comment by rochelle-norman** [comment]
@lubej Thanks, i'll close this
