### ISSUE TITLE
intermittent mnemonic confirm test failures

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-wallet-web#314]
```
  Create wallet
    ✓ Should have generated a mnemonic (3484ms)
    ✓ should not be able to submit without confirmation (70ms)
    ✓ Should open mnemonic confirmation (875ms)
    Confirm mnemonic
      ✓ Should pick word 1/5 (263ms)
      ✓ Should pick word 2/5 (180ms)
      ✓ Should pick word 3/5 (175ms)
      1) Should pick word 4/5
      2) Should pick word 5/5


  6 passing (31s)
  2 failing

  1) Create wallet
       Confirm mnemonic
         Should pick word 4/5:
     TestingLibraryElementError: Timed out retrying after 8000ms: Found multiple elements with the role "button" and name "nephew"

Here are the matching elements:





(If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).
      at Object.getElementError (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2048:17)
      at getElementError (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2936:22)
      at getMultipleElementsFoundError (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2940:10)
      at eval (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2991:13)
      at eval (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:3038:25)
      at baseCommandImpl (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1405:16)
      at commandImpl (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1408:40)
      at getValue (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1432:23)
      at resolveValue (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1472:35)

  2) Create wallet
       Confirm mnemonic
         Should pick word 5/5:
     TestingLibraryElementError: Timed out retrying after 8000ms: Found multiple elements with the role "button" and name "nephew"

Here are the matching elements:





(If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).
      at Object.getElementError (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2048:17)
      at getElementError (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2936:22)
      at getMultipleElementsFoundError (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2940:10)
      at eval (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:2991:13)
      at eval (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:3038:25)
      at baseCommandImpl (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1405:16)
      at commandImpl (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1408:40)
      at getValue (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1432:23)
      at resolveValue (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:1472:35)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        8                                                                                │
  │ Passing:      6                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     30 seconds                                                                       │
  │ Spec Ran:     create-wallet.ts                                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

from a run on develop

**Comment by lukaw3d** [comment]
we removed picking words: https://github.com/oasisprotocol/oasis-wallet-web/pull/527
