### ISSUE TITLE
UI: JS error while selecting an account from Ledger

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-wallet-web#383]
**What**
I tried to select an account from Ledger's Oasis app but saw an error.

**Repro**
Did not fully reproduce. I think this was intermittent. Maybe errors could be clearer (potentially already being addressed [here](https://github.com/oasisprotocol/oasis-wallet-web/issues/376#issuecomment-955777508))?

1. Ledger Oasis app open
2. Open wallet
3. Select account

```
Http response at 400 or 500 level
The above error occurred in task ur
    created by ur
    created by takeEvery(account/fetchAccount, ur)
    created by pr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, ur)
br
Error: Http response at 400 or 500 level
    at new D (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1047273)
    at Ft (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1070091)
    at _t.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1069321)
    at Ue (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1056104)
    at Be (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1055910)
    at xt (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1063399)
    at Tt (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1064180)
    at _t.r.W (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1065121)
    at _t.r.R (https://wallet.oasisprotocol.org/static/js/2.350dd49e.chunk.js:2:1065100)
```

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
