### ISSUE TITLE
A fatal error occurred

### ISSUE THREAD

**Issue by r4ngg4rut** [oasisprotocol/oasis-wallet-web#456]
Http response at 400 or 500 level
The above error occurred in task ft
    created by takeEvery(network/selectNetwork, ft)
    created by ht
Tasks cancelled due to error:
takeEvery(network/selectNetwork, ft)
Error: Http response at 400 or 500 level
    at new D (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1047878)
    at Ft (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1070696)
    at _t.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1069926)
    at Ue (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056709)
    at Be (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056515)
    at xt (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064004)
    at Tt (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064785)
    at _t.r.W (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065726)
    at _t.r.R (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065705)

**Comment by r4ngg4rut** [comment]
this error when create & open wallet on desktop (PC), but when i opened wallet on browser phone it is fine. (i use same mnemonic)

**Comment by pro-wh** [comment]
I just tried creating an opening a wallet on desktop, and I was able to get to the wallet screen fine. Maybe this was a temporary failure with the grpc-web node. Thanks for the report and the description of the steps where you encountered this.

We'll have to think about if there's anything we can do about this from the web wallet side.
