### ISSUE TITLE
Error: Http response at 400 or 500 level

### ISSUE THREAD

**Issue by pprabhu1978** [oasisprotocol/oasis-wallet-web#596]
Error: Http response at 400 or 500 level

The above error occurred in task loadDelegations
    created by fetchAccount
    created by fetchAccount
    created by takeEvery(staking/fetchAccount, fetchAccount)
    created by stakingSaga
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, fetchAccount)
takeEvery(staking/validatorSelected, getValidatorDetails)

Error: Http response at 400 or 500 level
    at new E (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:94905:13)
    at Y (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96430:33)
    at oc.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96404:25)
    at Ib (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:95551:22)
    at O (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:95537:3)
    at wc (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96058:21)
    at yc (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96125:9)
    at oc.push.n.W (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96070:3)
    at oc.push.n.R (https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96066:59)

**Comment by rebwar** [comment]
same issue

**Comment by exBigjohn** [comment]
Hello, I've had the same issue for a while now, when trying to reach the staking page ?

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
