### ISSUE TITLE
Wallet access

### ISSUE THREAD

**Issue by mdeghaim** [oasisprotocol/oasis-wallet-web#614]
Error: Http response at 400 or 500 level

The above error occurred in task selectNetwork
    created by takeEvery(network/selectNetwork, selectNetwork)
    created by networkSaga
Tasks cancelled due to error:
takeEvery(network/selectNetwork, selectNetwork)

Error: Http response at 400 or 500 level
    at new E (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:94905:13)
    at Y (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96430:33)
    at oc.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96404:25)
    at Ib (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95551:22)
    at O (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95537:3)
    at wc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96058:21)
    at yc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96125:9)
    at oc.push.n.W (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96070:3)
    at oc.push.n.R (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96066:59)

**Comment by xseth** [comment]
Same problem

**Comment by deleuze1995** [comment]
Hi! 
When I connect to the wallet from the Chrome extension, my ROSE have disappeared (the staking operation is also gone).

And when trying to connect to the wallet from the web, the following error appears:

Error: Http response at 400 or 500 level

The above error occurred in task selectNetwork
    created by takeEvery(network/selectNetwork, selectNetwork)
    created by networkSaga
Tasks cancelled due to error:
takeEvery(network/selectNetwork, selectNetwork)

Error: Http response at 400 or 500 level
    at new E (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:94905:13)
    at Y (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96430:33)
    at oc.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96404:25)
    at Ib (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95551:22)
    at O (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95537:3)
    at wc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96058:21)
    at yc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96125:9)
    at oc.push.n.W (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96070:3)
    at oc.push.n.R (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96066:59)

**Comment by xseth** [comment]
Same issue on Brave / Chrome / Safari 
Except on mobile device

Error: Http response at 400 or 500 level

The above error occurred in task selectNetwork
    created by takeEvery(network/selectNetwork, selectNetwork)
    created by networkSaga
Tasks cancelled due to error:
takeEvery(network/selectNetwork, selectNetwork)

Error: Http response at 400 or 500 level
    at new E (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:94905:13)
    at Y (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96430:33)
    at oc.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96404:25)
    at Ib (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95551:22)
    at O (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95537:3)
    at wc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96058:21)
    at yc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96125:9)
    at oc.push.n.W (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96070:3)
    at oc.push.n.R (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96066:59)

**Comment by deleuze1995** [comment]
Fixed! The wallet is accessible again and all the ROSE appear 😄

**Comment by xseth** [comment]
Not working for me on macOS

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
