### ISSUE TITLE
Error when loading my account:  "A fatal error occurred"

### ISSUE THREAD

**Issue by rusen14** [oasisprotocol/oasis-wallet-web#616]
Can't load my account after writing my mnemonic on web wallet, even though my mnemonic is true. Here is the error code:

Error: Http response at 400 or 500 level

The above error occurred in task loadDelegations
    created by fetchAccount
    created by fetchAccount
    created by takeEvery(staking/fetchAccount, fetchAccount)
    created by stakingSaga
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, fetchAccount)
takeEvery(staking/validatorSelected, getValidatorDetails)

Error: Http response at 400 or 500 level
    at new E (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:94905:13)
    at Y (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96430:33)
    at oc.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96404:25)
    at Ib (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95551:22)
    at O (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95537:3)
    at wc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96058:21)
    at yc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96125:9)
    at oc.push.n.W (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96070:3)
    at oc.push.n.R (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96066:59)

**Comment by rusen14** [comment]
anyhow it now opens after refreshing like 10 times. Though you might want to look at this error as it got me worried for like 5 minutes :d
