### ISSUE TITLE
Wallet ERROR for several days

### ISSUE THREAD

**Issue by xseth** [oasisprotocol/oasis-wallet-web#617]
Hello, I am unable to access the wallet for several days!
I am on macOS I have tried everything, various browsers: Brave / Chrome / Safari. I also reset all the settings and cache of the browsers... There is nothing to do, I have permanently this error

Error: Http response at 400 or 500 level

The above error occurred in task selectNetwork
    created by takeEvery(network/selectNetwork, selectNetwork)
    created by networkSaga
Tasks cancelled due to error:
takeEvery(network/selectNetwork, selectNetwork)

Error: Http response at 400 or 500 level
    at new E (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:94905:13)
    at Y (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96430:33)
    at oc.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96404:25)
    at Ib (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95551:22)
    at O (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95537:3)
    at wc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96058:21)
    at yc (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96125:9)
    at oc.push.n.W (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96070:3)
    at oc.push.n.R (https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96066:59)

**Comment by HockeyCanada** [comment]
Same with me wallet  it is showing total balance of zero.    But on oasis scan it shows up.  

That being said I can’t send any
or stake any.  

Wallet keeps showing error couldn’t load account information may be missing or out of date

**Comment by Axtum** [comment]
Wallet keeps showing error couldn’t load account information may be missing or out of date
0 in my wallet

**Comment by xseth** [comment]
I have tried everything!!! 
erase the cache of my browser, reset my browser completely... And this on Brave / Chrome / Firefox / Safari !!!
there is nothing to do it still doesn't work it's really annoying

**Comment by xseth** [comment]
This project is abandoned ??? 
A lot of people have problems and the devs don't seem to react...

**Comment by xseth** [comment]
in fact it was my fault. 
I forgot, a long time ago I had created a local redirection of all .dev domains on my mac
I deleted it in /etc/resolver/dev now the oasis.dev link responds correctly... 
Everything is solved :)
