### ISSUE TITLE
Error wallet

### ISSUE THREAD

**Issue by xseth** [oasisprotocol/oasis-wallet-web#692]
I think the problem is that I cannot solve : grpc.oasis.dev

Failed to load resource: net::ERR_ADDRESS_UNREACHABLE

Error: Http response at 400 or 500 level

The above error occurred in task selectNetwork
    created by takeEvery(network/selectNetwork, selectNetwork)
    created by networkSaga
Tasks cancelled due to error:
takeEvery(network/selectNetwork, selectNetwork)

Error: Http response at 400 or 500 level
    at new E (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:94905:13)
    at Y (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:96430:33)
    at oc.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:96404:25)
    at Ib (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:95551:22)
    at O (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:95537:3)
    at wc (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:96058:21)
    at yc (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:96125:9)
    at oc.push.n.W (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:96070:3)
    at oc.push.n.R (https://wallet.oasisprotocol.org/static/js/2.4b9d1ee8.chunk.js:96066:59)

**Comment by xseth** [comment]
yet I manage to solve with nslookup

**Comment by xseth** [comment]
in fact it was my fault. 
I forgot, a long time ago I had created a local redirection of all .dev domains on my mac
I deleted it in /etc/resolver/dev now the oasis.dev link responds correctly... 
Everything is solved :)
