### ISSUE TITLE
DateFormatter Failing Unit Tests

### ISSUE THREAD

**Issue by memoriesadrift** [oasisprotocol/oasis-wallet-web#948]
# Issue
Running Jest tests locally on a clean build of the repo leads to tests failing due to incorrectly formatted dates compared to snapshots.

# Steps to Replicate
1.  `git pull`
2. `yarn install`
3. `yarn test`

# Possible Causes
It seems tests running in Node.js break internationalization which relies on the browser, see [similar issue](https://www.basefactor.com/javascript-es6-intl-not-working-properly-when-running-jest-tests) and provided solutions.

# Test Output
```
$ yarn test
yarn run v1.22.19
$ jest --color
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 FAIL   Web Wallet  src/app/components/DateFormatter/__tests__/index.test.tsx
  ● intlDateTimeFormat › should format date to human readable format

    expect(received).toEqual(expected) // deep equality

    Expected: "7/4/2022, 10:57:31 AM"
    Received: "04/07/2022, 10:57:31"

       5 | describe('intlDateTimeFormat', () => {
       6 |   it('should format date to human readable format', () => {
    >  7 |     expect(intlDateTimeFormat(1656932251)).toEqual('7/4/2022, 10:57:31 AM')
         |                                            ^
       8 |     expect(intlDateTimeFormat(new Date(Date.UTC(2022, 6, 27, 8, 33, 10)))).toEqual('7/27/2022, 8:33:10 AM')
       9 |   })
      10 | })

      at Object.<anonymous> (src/app/components/DateFormatter/__tests__/index.test.tsx:7:44)

  ● <DateFormatter  /> › should render component with formatted date

    TestingLibraryElementError: Unable to find an element with the text: 7/4/2022, 10:57:31 AM. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    Ignored nodes: comments, <script />, <style />
    <body>
      <div>
        04/07/2022, 10:57:31
      </div>
    </body>

      13 |   it('should render component with formatted date', () => {
      14 |     render(<DateFormatter date={1656932251} />)
    > 15 |     expect(screen.getByText('7/4/2022, 10:57:31 AM')).toBeInTheDocument()
         |                   ^
      16 |   })
      17 | })
      18 |

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at node_modules/@testing-library/dom/dist/query-helpers.js:90:38
      at node_modules/@testing-library/dom/dist/query-helpers.js:62:17
      at getByText (node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
      at Object.<anonymous> (src/app/components/DateFormatter/__tests__/index.test.tsx:15:19)

 FAIL   Web Wallet  src/app/components/Footer/__tests__/index.test.tsx (5.243 s)
  ● <Footer /> › should render mobile version of footer

    expect(received).toMatchSnapshot()

    Snapshot name: `<Footer /> should render mobile version of footer 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -248,11 +248,11 @@
            class="c2"
            href="https://github.com/oasisprotocol/oasis-wallet-web/commit/sha0000000000000000000000000000000000000"
          >
            sha0000
          </a>
    -      built at 1/1/1970, 12:00:00 AM
    +      built at 01/01/1970, 00:00:00
          <div
            class="c4"
          >
            Powered by Oasis Scan API & Oasis gRPC
          </div>

      62 |     renderComponent(store, 'small')
      63 |
    > 64 |     expect(screen.getByRole('contentinfo')).toMatchSnapshot()
         |                                             ^
      65 |   })
      66 | })
      67 |

      at Object.<anonymous> (src/app/components/Footer/__tests__/index.test.tsx:64:45)

 › 1 snapshot failed.
 PASS   Web Wallet  src/app/pages/AccountPage/__tests__/index.test.tsx (6.175 s)
 FAIL   Web Wallet  src/app/components/Transaction/__tests__/index.test.tsx (6.535 s)
  ● <Transaction  /> › should match snapshot

    expect(received).toMatchSnapshot()

    Snapshot name: `<Transaction  /> should match snapshot 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -614,11 +614,11 @@
                      common.time
                    </span>
                    <span
                      class="c14"
                    >
    -                 4/10/2021, 1:30:55 AM
    +                 10/04/2021, 01:30:55
                    </span>
                  </div>
                </div>
              </div>
            </div>

      72 |   it('should match snapshot', () => {
      73 |     const component = renderComponent(store, ref, transaction, network)
    > 74 |     expect(component.container.firstChild).toMatchSnapshot()
         |                                            ^
      75 |   })
      76 |
      77 |   it('should copy an address and tx hash value to clipboard', () => {

      at Object.<anonymous> (src/app/components/Transaction/__tests__/index.test.tsx:74:44)

  ● <Transaction  /> › should handle unknown transaction types gracefully

    expect(received).toMatchSnapshot()

    Snapshot name: `<Transaction  /> should handle unknown transaction types gracefully 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -614,11 +614,11 @@
                      common.time
                    </span>
                    <span
                      class="c14"
                    >
    -                 4/10/2021, 1:30:55 AM
    +                 10/04/2021, 01:30:55
                    </span>
                  </div>
                </div>
              </div>
            </div>

      107 |       network,
      108 |     )
    > 109 |     expect(component.container.firstChild).toMatchSnapshot()
          |                                            ^
      110 |   })
      111 |
      112 |   it('should not render a link when address is undefined', () => {

      at Object.<anonymous> (src/app/components/Transaction/__tests__/index.test.tsx:109:44)

 › 2 snapshots failed.
 PASS   Web Wallet  src/app/pages/StakingPage/Features/ValidatorList/__tests__/index.test.tsx (7.039 s)
 PASS   Web Wallet  src/app/pages/StakingPage/Features/DelegationList/__tests__/ActiveDelegationList.test.tsx
 PASS   Web Wallet  src/app/pages/CreateWalletPage/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/pages/OpenWalletPage/Features/FromMnemonic/__tests__/index.test.tsx (8.938 s)
 PASS   Web Wallet  src/app/pages/OpenWalletPage/Features/FromPrivateKey/__tests__/index.test.tsx (9.537 s)
 PASS   Web Wallet  src/app/components/AddEscrowForm/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/pages/StakingPage/Features/DelegationList/__tests__/DebondingDelegationList.test.tsx
 PASS   Web Wallet  src/app/pages/OpenWalletPage/Features/FromLedger/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/components/ReclaimEscrowForm/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/components/MobileFooterNavigation/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/pages/StakingPage/Features/ValidatorMediaInfo/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/pages/AccountPage/Features/SendTransaction/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/components/FatalErrorHandler/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/components/Toolbar/Features/NetworkSelector/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/components/Toolbar/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/components/Sidebar/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/state/wallet/saga.test.ts
 PASS   Web Wallet  src/styles/theme/__tests__/ThemeProvider.test.tsx
 PASS   Web Wallet  src/app/pages/StakingPage/Features/CommissionBounds/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/components/Toolbar/Features/AccountSelector/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/state/staking/saga.test.ts
 PASS   Web Wallet  src/app/components/AmountFormatter/__tests__/index.test.tsx
 PASS   Web Wallet  src/vendors/__tests__/monitor.test.ts
 PASS   Web Wallet  src/app/components/ShortAddress/__tests__/index.test.tsx
 PASS   Web Wallet  src/app/state/transaction/saga.test.ts
 PASS   Web Wallet  src/app/state/ledger/saga.test.ts
 PASS   Web Wallet  src/app/components/PrettyAddress/__tests__/index.test.tsx
 PASS   Web Wallet  src/utils/__tests__/loadable.test.tsx
 PASS   Web Wallet  src/vendors/__tests__/oasisscan.test.ts
 PASS   Web Wallet  src/app/lib/transaction.test.ts
 PASS   Web Wallet  src/app/lib/ledger.test.ts
 PASS   Web Wallet  src/app/state/network/saga.test.ts
 PASS   Web Wallet  src/vendors/__tests__/throwAPIErrors.test.ts
 PASS   Web Wallet  src/app/state/account/saga.test.ts
 PASS   Web Wallet  src/app/useRouteRedirects.test.ts
 PASS   Web Wallet  src/store/__tests__/reducer.test.ts
 PASS   Web Wallet  src/app/lib/helpers.test.ts
 PASS   Web Wallet  src/types/__tests__/TypeSafeDataTable.test.tsx
 PASS   Web Wallet  src/locales/__tests__/strict-translation-keys.test.tsx
 PASS   Web Wallet  src/styles/theme/__tests__/utils.test.ts
 PASS   Web Wallet  src/locales/__tests__/i18n.test.ts
 PASS   Web Wallet  src/utils/@reduxjs/toolkit.test.tsx

Summary of all failing tests
 FAIL  src/app/components/DateFormatter/__tests__/index.test.tsx
  ● intlDateTimeFormat › should format date to human readable format

    expect(received).toEqual(expected) // deep equality

    Expected: "7/4/2022, 10:57:31 AM"
    Received: "04/07/2022, 10:57:31"

       5 | describe('intlDateTimeFormat', () => {
       6 |   it('should format date to human readable format', () => {
    >  7 |     expect(intlDateTimeFormat(1656932251)).toEqual('7/4/2022, 10:57:31 AM')
         |                                            ^
       8 |     expect(intlDateTimeFormat(new Date(Date.UTC(2022, 6, 27, 8, 33, 10)))).toEqual('7/27/2022, 8:33:10 AM')
       9 |   })
      10 | })

      at Object.<anonymous> (src/app/components/DateFormatter/__tests__/index.test.tsx:7:44)

  ● <DateFormatter  /> › should render component with formatted date

    TestingLibraryElementError: Unable to find an element with the text: 7/4/2022, 10:57:31 AM. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    Ignored nodes: comments, <script />, <style />
    <body>
      <div>
        04/07/2022, 10:57:31
      </div>
    </body>

      13 |   it('should render component with formatted date', () => {
      14 |     render(<DateFormatter date={1656932251} />)
    > 15 |     expect(screen.getByText('7/4/2022, 10:57:31 AM')).toBeInTheDocument()
         |                   ^
      16 |   })
      17 | })
      18 |

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at node_modules/@testing-library/dom/dist/query-helpers.js:90:38
      at node_modules/@testing-library/dom/dist/query-helpers.js:62:17
      at getByText (node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
      at Object.<anonymous> (src/app/components/DateFormatter/__tests__/index.test.tsx:15:19)

 FAIL  src/app/components/Footer/__tests__/index.test.tsx (5.243 s)
  ● <Footer /> › should render mobile version of footer

    expect(received).toMatchSnapshot()

    Snapshot name: `<Footer /> should render mobile version of footer 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -248,11 +248,11 @@
            class="c2"
            href="https://github.com/oasisprotocol/oasis-wallet-web/commit/sha0000000000000000000000000000000000000"
          >
            sha0000
          </a>
    -      built at 1/1/1970, 12:00:00 AM
    +      built at 01/01/1970, 00:00:00
          <div
            class="c4"
          >
            Powered by Oasis Scan API & Oasis gRPC
          </div>

      62 |     renderComponent(store, 'small')
      63 |
    > 64 |     expect(screen.getByRole('contentinfo')).toMatchSnapshot()
         |                                             ^
      65 |   })
      66 | })
      67 |

      at Object.<anonymous> (src/app/components/Footer/__tests__/index.test.tsx:64:45)

 FAIL  src/app/components/Transaction/__tests__/index.test.tsx (6.535 s)
  ● <Transaction  /> › should match snapshot

    expect(received).toMatchSnapshot()

    Snapshot name: `<Transaction  /> should match snapshot 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -614,11 +614,11 @@
                      common.time
                    </span>
                    <span
                      class="c14"
                    >
    -                 4/10/2021, 1:30:55 AM
    +                 10/04/2021, 01:30:55
                    </span>
                  </div>
                </div>
              </div>
            </div>

      72 |   it('should match snapshot', () => {
      73 |     const component = renderComponent(store, ref, transaction, network)
    > 74 |     expect(component.container.firstChild).toMatchSnapshot()
         |                                            ^
      75 |   })
      76 |
      77 |   it('should copy an address and tx hash value to clipboard', () => {

      at Object.<anonymous> (src/app/components/Transaction/__tests__/index.test.tsx:74:44)

  ● <Transaction  /> › should handle unknown transaction types gracefully

    expect(received).toMatchSnapshot()

    Snapshot name: `<Transaction  /> should handle unknown transaction types gracefully 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -614,11 +614,11 @@
                      common.time
                    </span>
                    <span
                      class="c14"
                    >
    -                 4/10/2021, 1:30:55 AM
    +                 10/04/2021, 01:30:55
                    </span>
                  </div>
                </div>
              </div>
            </div>

      107 |       network,
      108 |     )
    > 109 |     expect(component.container.firstChild).toMatchSnapshot()
          |                                            ^
      110 |   })
      111 |
      112 |   it('should not render a link when address is undefined', () => {

      at Object.<anonymous> (src/app/components/Transaction/__tests__/index.test.tsx:109:44)


Snapshot Summary
 › 3 snapshots failed from 2 test suites. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 3 failed, 3 skipped, 44 passed, 47 of 50 total
Tests:       5 failed, 4 skipped, 1 todo, 155 passed, 165 total
Snapshots:   3 failed, 39 passed, 42 total
Time:        18.6 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lukaw3d** [comment]
Thank you for the bug report!

My locale settings in linux don't seem to propagate to nodejs :/ I think the easiest to understand fix would be:
https://github.com/oasisprotocol/oasis-wallet-web/blob/381f7e67507d4e079ce719092e1a89ac211890d3/src/app/components/DateFormatter/index.tsx#L12
```ts
export const dateFormat = new Intl.DateTimeFormat(process?.env?.NODE_ENV === 'test' ? 'en-US' : undefined, {
```

Related: we're formatting ROSE amounts with Intl, but I'm replacing that with BigNumber.toFormat(1..15)
https://github.com/oasisprotocol/oasis-wallet-web/blob/381f7e67507d4e079ce719092e1a89ac211890d3/src/app/components/AmountFormatter/index.tsx#L23-L26

@buberdds thoughts?

**Comment by buberdds** [comment]
My preference is to have the same build artefact per env, but we already have `process?.env?.NODE_ENV` checks in DateFormatter so 🤷‍♂️  Another alternative would be mock Intl.DateFormat globally in setupTests probably, but I am fine with merging `process?.env?.NODE_ENV === 'test' ? 'en-US' : undefined` 🖖
